### ISSUE TITLE
name 'ouput_dir' is not defined

### ISSUE THREAD

**Issue by JohnWentao** [sblanky/autobetsi#1]
Thanks so much for making this code.
I found a mistake in `autobetsi.py` when try to use it.
```
    mkdir(ouput_dir)
NameError: name 'ouput_dir' is not defined
```

**Comment by sblanky** [comment]
Thanks for trying out the software! Could you give me a little more information? Are you using the code as it says in the README or adapting it? Which line is this error from?

Thanks,
Scott

edit: Aaah, I see it. Working on it!

**Comment by JohnWentao** [comment]
[autobetsi](https://github.com/sblanky/autobetsi)/[autobetsi](https://github.com/sblanky/autobetsi/tree/main/autobetsi)/autobetsi.py
yes, haha. It's in line 84.
Wonderful software!!

John

**Comment by sblanky** [comment]
Should work after most recent commit. 47fe95f8ac0e84c92f7f4f7c868348a7c82c33f0

:)

Let me know!

**Comment by JohnWentao** [comment]
Yes, it works now!

Thank you,
John

**Comment by sblanky** [comment]
Brilliant, if you see any more ways to improve let me know or submit a pull request!
